In [1]:
# 1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.__version__

'1.20.3'

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"

# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


# 2 subarreglos con 3 sub-sub-arreglos cada uno
# con 5 elementos cada uno
a = np.random.random((2, 3, 5))

In [5]:
#4. Print a.
print(a)

[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846e-01]]]


In [6]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

In [7]:
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [8]:
#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size)
print(b.size)

30
30


In [9]:
#8. Are you able to add a and b? Why or why not?

np.add(a, b)

# Although the size is the same, the matrix shape is not the same to add them together. 
# a matrix has a shape of 2x3x5 and b matrix has a shape of 5x2x3.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [10]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [11]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". 
# But why does it work now?

d = np.add(a, c)
print(d)

[[[1.87036108 1.18868514 1.36016581 1.99133296 1.1715027 ]
  [1.61156748 1.04635733 1.46429825 1.88148193 1.68425146]
  [1.57967838 1.65077184 1.5537377  1.70652388 1.72890844]]

 [[1.97984773 1.61028327 1.25384803 1.87085581 1.06204751]
  [1.72055304 1.79008234 1.77210679 1.86061038 1.24936088]
  [1.00078733 1.32914751 1.05642654 1.21930404 1.39788085]]]


In [12]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)
(2, 3, 5)


In [13]:
#11. Print a and d. 
# Notice the difference and relation of the two array in terms of the values? Explain.

print(a)
print('------------')
print(d)

# both arrays have the same shape and matrix d is the sum of matrix a plus the ones
# and the a matrix has the random values created over 0 and 1.

[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846e-01]]]
------------
[[[1.87036108 1.18868514 1.36016581 1.99133296 1.1715027 ]
  [1.61156748 1.04635733 1.46429825 1.88148193 1.68425146]
  [1.57967838 1.65077184 1.5537377  1.70652388 1.72890844]]

 [[1.97984773 1.61028327 1.25384803 1.87085581 1.06204751]
  [1.72055304 1.79008234 1.77210679 1.86061038 1.24936088]
  [1.00078733 1.32914751 1.05642654 1.21930404 1.39788085]]]


In [14]:
#12. Multiply a and c. Assign the result to e.
e = a * c
print(e)

[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846e-01]]]


In [16]:
#13. Does e equal to a? Why or why not?

print(a)
print('---------------')
print(e)

# a and e are equal because matrix e is the result of multiplying a by c, and c is a matrix of ones.

[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846e-01]]]
---------------
[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846

In [17]:
#14. Identify the max, min, and mean values in d. 
# Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9913329591165625
1.0007873346209388
1.5220922142494608


In [19]:
#15. Now we want to label the values in d. 
# First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty([2, 3, 5])
print(f)

[[[8.70361075e-01 1.88685144e-01 3.60165814e-01 9.91332959e-01
   1.71502695e-01]
  [6.11567477e-01 4.63573269e-02 4.64298253e-01 8.81481931e-01
   6.84251463e-01]
  [5.79678383e-01 6.50771843e-01 5.53737696e-01 7.06523876e-01
   7.28908441e-01]]

 [[9.79847728e-01 6.10283274e-01 2.53848027e-01 8.70855814e-01
   6.20475132e-02]
  [7.20553035e-01 7.90082336e-01 7.72106791e-01 8.60610381e-01
   2.49360884e-01]
  [7.87334621e-04 3.29147508e-01 5.64265366e-02 2.19304041e-01
   3.97880846e-01]]]


In [21]:
f = np.where((d > d_min) & (d < d_mean), 25, 
             np.where((d > d_mean) & (d < d_max), 75, 
                      np.where(d == d_mean, 50, 
                               np.where(d == d_min, 0, 
                                        np.where(d == d_max, 100, None)))))
print(f)

[[[75 25 25 100 25]
  [75 25 25 75 75]
  [75 75 75 75 75]]

 [[75 75 25 75 25]
  [75 75 75 75 25]
  [0 25 25 25 25]]]


In [22]:
print(f)

[[[75 25 25 100 25]
  [75 25 25 75 75]
  [75 75 75 75 75]]

 [[75 75 25 75 25]
  [75 75 75 75 25]
  [0 25 25 25 25]]]


In [28]:
# A=100, B=75, C=50, D=25, E=0

f_bonus = np.where((d > d_min) & (d < d_mean), 'D', 
              np.where((d > d_mean) & (d < d_max), 'B', 
                       np.where(d == d_mean, 'C', 
                                np.where(d == d_min, 'E', 
                                         np.where(d == d_max, 'A', None)))))
print(f_bonus)

[[['B' 'D' 'D' 'A' 'D']
  ['B' 'D' 'D' 'B' 'B']
  ['B' 'B' 'B' 'B' 'B']]

 [['B' 'B' 'D' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['E' 'D' 'D' 'D' 'D']]]
